{
    'name': 'Zigma ERP',
    'version': '17.0.1.0.0',
    'summary': 'Custom ERP Module for Zigma',
    'description': 'Module to manage item details and product codes. Module to manage quotations with item and product lines',
    'author': 'RedRuby Technologies',
    'website': 'https://redrubytechnologies.com/',
    'category': 'Uncategorized',
    'depends': ['stock','base', 'base_setup', 'sale','product'],
  
    'data': [
        # 'data/delivery_booking_sequence.xml',
        'data/sequence_data.xml',
        'data/fiscal_sequence_update.xml',
        'data/outward_type_data.xml',
        # 'report/quotation_to_customer.xml',
        # 'report/quotation_report.xml',
        # 'report/quotation_report_manager.xml',
        "report/custom_label_zigma.xml",
        'security/security.xml',
        'security/ir.model.access.csv',
        # 'views/res_partner_oem.xml',
        # 'views/product_views.xml',
        # 'views/item_details_views.xml',
        # 'data/email_template_quotation_to_customer.xml',
        # 'data/email_template_quotation_approval.xml',
        # 'views/customer_enq.xml',
        # 'views/order_enq.xml',
        # 'views/quotation_views.xml',
        # 'views/quotation_version_history_view.xml',
        # 'views/consignee_separation_views.xml',
        # 'views/consignee_bulk_import_wizard_views.xml',
        # 'views/financial_year.xml',
        'views/bulk_print_wizard_views.xml',
        # 'views/stock_tranfer_views.xml',
        # 'views/test.xml',

        # "views/stock_picking_views.xml",
        # 'views/menu.xml',
        # 'views/sale_order_views.xml',
        # "views/purchase_views.xml",
        # "views/ewaybill.xml",
        # "views/demo_product.xml",
        # 'views/lot_reassign_wizard_views.xml',
        'views/bulk_serial_upload_wizard_views.xml',
        # 'views/stock_lot_generate_wizard_views.xml',
        # 'views/partner_address_bulk_import_views.xml',
        # 'views/delivery_booking_views.xml',
        # 'views/sale_order_summary_views.xml',
        # 'views/menu_views.xml',
        # 'views/duties_taxes_views.xml',
        # 'views/sundry_debtors_views.xml',
        # 'views/sundry_creditors_views.xml',
        # 'views/account_move_masters_views.xml',
        # 'views/elcot_po_wizard_views.xml',
        # 'views/dispatch_views.xml',

    ],
    'assets': {
        
        'web.assets_backend': [
            # 'zigma_erp/static/src/**/*.js',
            # 'zigma_erp/static/src/js/purchase_dashboard.js',
            'zigma_erp/static/src/js/po_attachment_widget.js',
            # 'zigma_erp/static/src/js/save_notify.js',
            # 'zigma_erp/static/src/js/serial_assign_poller.js',
            # 'zigma_erp/static/src/js/sale_dashboard.js',
            # 'zigma_erp/static/src/js/sale_listview.js',
            # 'zigma_erp/static/src/js/receipt_dashboard.js',
            # 'zigma_erp/static/src/js/delivery_dashboard.js',
            # 'zigma_erp/static/src/js/delivery_booking_dashboard.js',
            # 'zigma_erp/static/src/js/delivery_booking_listview.js',
            # 'zigma_erp/static/src/js/invoice_dashboard.js',
            # 'zigma_erp/static/src/js/invoice_listview.js',
            # 'zigma_erp/static/src/js/purchase_indent_dashboard.js',
            # 'zigma_erp/static/src/js/purchase_indent_listview.js',
            # 'zigma_erp/static/src/js/purchase_order_dashboard.js',
            # 'zigma_erp/static/src/js/purchase_order_listview.js',
            # 'zigma_erp/static/src/js/all_purchase_order_dashboard.js',
            # 'zigma_erp/static/src/js/all_purchase_order_listview.js',
            # 'zigma_erp/static/src/js/receipt_listview.js',
            # 'zigma_erp/static/src/js/consignee_dashboard.js',
            # 'zigma_erp/static/src/js/consignee_listview.js',
            # 'zigma_erp/static/src/js/customer_enq_dashboard.js',
            # 'zigma_erp/static/src/js/customer_enq_listview.js',
            'zigma_erp/static/src/js/attachment_size_widget.js',
            # 'zigma_erp/static/src/js/consignee_bulk_import_button.js',
            # 'zigma_erp/static/src/js/stock_move_one2many.js',
            # 'zigma_erp/static/src/js/demo_one2many.js',
            'zigma_erp/static/src/**/*.xml',
            'zigma_erp/static/src/css/enquiry_popup_style.scss',

        ],
        
    },
    'installable': True,
    'application': True,

    'external_dependencies': {
        'python': ['openpyxl'],
    },

}
